<a href="https://colab.research.google.com/github/Arth9vansola/Aero/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
n_array = np.array([1,2,3])

In [5]:
print(n_array)

[1 2 3]


In [8]:
nl_array = np.zeros((2,3))
print(nl_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
nl2_array = np.ones((2,3))
print(nl2_array)

[[1. 1. 1.]
 [1. 1. 1.]]


#full array


In [12]:
full_array = np.full((10,10),7)
print(full_array)

[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


# to create sequence of number arange(start,stop,step)

In [14]:
array1 = np.arange(1,10,3)
print(array1)

[ 1  4  7 10]


# identity matrices



In [18]:
identity_matrices = np.eye((3))
print(identity_matrices)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
